FROM tensorflow/tensorflow:2.3.1-gpu

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
RUN apt-get update
RUN apt-get install 'ffmpeg'\
    'libsm6'\ 
    'libxext6'\
    'libgl1-mesa-dev' -y

WORKDIR /work
CMD ["make", "jupyter"]
